# -*- coding: utf-8 -*-
#
# project-template documentation build configuration file, created by
# sphinx-quickstart on Mon Jan 18 14:44:12 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, os.path.abspath("sphinxext"))
# import sphinx_gallery

# import sphinx_rtd_theme

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "4.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    # "sphinx_gallery.gen_gallery",
    # "sphinx.ext.linkcode",
    "sphinxcontrib.bibtex",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "numpydoc",
    "myst_nb",
    "sphinx_sitemap",
    "sphinx_favicon",
    "override_pst_pagetoc",
]

# this is needed for some reason...
# see https://github.com/numpy/numpydoc/issues/69
numpydoc_show_class_members = False
numpydoc_show_inherited_class_members = False
numpydoc_class_members_toctree = False

# bibtex file
bibtex_bibfiles = ["references.bib"]
bibtex_encoding = "utf-8-sig"
bibtex_reference_style = "author_year"
bibtex_default_style = "plain"

# pngmath / imgmath compatibility layer for different sphinx versions

# if LooseVersion(sphinx.__version__) < LooseVersion('1.4'):
#     extensions.append('sphinx.ext.pngmath')
# else:
#     extensions.append('sphinx.ext.imgmath')
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

# autodoc_default_flags = ['members', 'inherited-members']

# -- Options for autodoc ------------------------------------------------------

autodoc_default_options = {
    "members": True,
    "inherited-members": True,
}

autodoc_type_aliases = {
    "npt.ArrayLike": "npt.ArrayLike",
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# generate autosummary even if no references
autosummary_generate = True

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# Generate the plots for the gallery
plot_gallery = "True"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "ktch"
copyright = "2020-{0}, Koji Noshita".format(datetime.datetime.now().year)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
from ktch import __version__

version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# Version match for version switcher
# When building with sphinx-multiversion, use the environment variable
# to get the correct version being built (e.g., "main" -> "dev", "v0.6.1" -> "0.6.1")
_smv_name = os.environ.get("SPHINX_MULTIVERSION_NAME", "")

# Debug output for CI
if os.environ.get("CI"):
    print(f"[DEBUG] SPHINX_MULTIVERSION_NAME={_smv_name!r}")
    print(f"[DEBUG] __version__={version!r}")

if _smv_name == "main":
    version_match = "dev"
elif _smv_name.startswith("v"):
    # Strip 'v' prefix: "v0.6.1" -> "0.6.1"
    version_match = _smv_name[1:]
elif "dev" in version or "rc" in version or "a" in version or "b" in version:
    # Fallback for non-multiversion builds (local development)
    version_match = "dev"
else:
    version_match = version

# Override version/release when building specific tags with sphinx-multiversion
# This ensures DOCUMENTATION_OPTIONS.VERSION matches the documented version,
# which prevents the "unstable development version" banner from showing incorrectly
if _smv_name.startswith("v"):
    version = version_match
    release = version_match

if os.environ.get("CI"):
    print(f"[DEBUG] version_match={version_match!r}")
    print(f"[DEBUG] version (after override)={version!r}")

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "_templates", "README.md"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Custom style
# html_style = 'css/ktch.css'
# html_css_files = ["css/ktch.css"]

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

html_js_files = [
    "js/copybutton.js",
    "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js",
]

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'sphinx_rtd_theme'
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}
html_theme_options = {
    # "logo_link": "index",
    "github_url": "https://github.com/noshita/ktch",
    # "collapse_navigation": True,
    # "external_links": [
    #     {"name": "Learn", "url": "https://numpy.org/numpy-tutorials/"}
    #     ],
    "analytics": {"google_analytics_id": "G-6WZ5SLD7H7"},
    "article_header_end": ["notebook-download"],
    # Version switcher configuration
    "switcher": {
        # Use relative path for local builds, absolute URL for production
        "json_url": (
            "https://doc.ktch.dev/dev/_static/versions.json"
            if os.environ.get("READTHEDOCS") or os.environ.get("CI")
            else "_static/versions.json"
        ),
        "version_match": version_match,
    },
    "navbar_start": ["navbar-logo", "version-switcher"],
    "show_version_warning_banner": True,
    # Disable JSON validation for local builds (URL may not exist yet)
    "check_switcher": bool(os.environ.get("CI")),
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None
html_logo = "_static/img/logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "_static/img/favicon_32.png"
favicons = [
    {"href": "favicon.svg"},  # => use `_static/icon.svg`
    {"href": "favicon_32.png"},
    {
        "rel": "apple-touch-icon",
        "href": "apple-touch-icon.png",
    },
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []
html_extra_path = ["robots.txt"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
html_use_opensearch = "https://doc.ktch.dev/"

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "ktchdoc"

# sphinx-sitemap configuration for multi-version docs
html_baseurl = "https://doc.ktch.dev/"
sitemap_locales = [None]

# Set sitemap URL scheme based on build target
# Each version generates sitemap with its own path
if _smv_name == "main":
    # dev version: /dev/
    sitemap_url_scheme = "dev/{link}"
elif _smv_name.startswith("v"):
    # Tagged releases: use version number without 'v' prefix
    # e.g., "v0.6.1" -> "0.6.1/{link}"
    _sitemap_version = _smv_name[1:]
    sitemap_url_scheme = f"{_sitemap_version}/{{link}}"
else:
    # Local/single-version builds
    sitemap_url_scheme = "{link}"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ("index", "ktch.tex", "ktchDocumentation", "Koji Noshita", "manual"),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", "ktch", "ktch Documentation", ["Noshita, Koji"], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "ktch",
        "ktch Documentation",
        "Koji Noshita",
        "ktch",
        "ktch is a python package for model-based morphometrics.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False


# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx configuration
intersphinx_mapping = {
    "python": ("https://docs.python.org/{.major}".format(sys.version_info), None),
    "numpy": ("https://docs.scipy.org/doc/numpy/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    "matplotlib": ("https://matplotlib.org/", None),
    "sklearn": ("http://scikit-learn.org/stable", None),
    "pandas": ("http://pandas.pydata.org/pandas-docs/stable/", None),
    "seaborn": ("https://seaborn.pydata.org/", None),
    "xarray": ("https://xarray.pydata.org/en/stable/", None),
}

# sphinx-gallery configuration
# sphinx_gallery_conf = {
#     "doc_module": "ktch",
#     "examples_dirs": "../notebooks",
#     "backreferences_dir": os.path.join("generated"),
#     "reference_url": {"ktch": None},
# }

# def setup(app):
#     # a copy button to copy snippet of code from the documentation
#     app.add_javascript('js/copybutton.js')


# for myst-nb
# MyST Markdown notebooks (.md with jupytext header) are processed directly
source_suffix = {
    ".rst": "restructuredtext",
    ".ipynb": "myst-nb",
    ".myst": "myst-nb",
    ".md": "myst-nb",
}
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]
myst_url_schemes = ("http", "https", "mailto")
nb_execution_timeout = 300

# -- sphinx-multiversion configuration ---------------------------------------
# Load version info from versions.json (single source of truth)

import json
import re

_versions_path = Path(__file__).parent / "_static" / "versions.json"
if _versions_path.exists():
    with open(_versions_path) as f:
        _versions_data = json.load(f)

    # Extract version tags (e.g., "0.7.0" -> "v0.7.0")
    # Skip "dev" version as it corresponds to the main branch
    _tag_versions = [
        f"v{entry['version']}"
        for entry in _versions_data
        if entry.get("version") and entry["version"] != "dev"
    ]

    # Build regex pattern: ^(v0\.6\.1|v0\.7\.0)$
    if _tag_versions:
        _escaped = [re.escape(v) for v in _tag_versions]
        smv_tag_whitelist = f"^({'|'.join(_escaped)})$"
    else:
        smv_tag_whitelist = r"^$"  # Match nothing
else:
    # Fallback for environments without versions.json
    smv_tag_whitelist = r"^v\d+\.\d+\.\d+$"

# Branch whitelist: only main branch
smv_branch_whitelist = r"^main$"
# Remote whitelist
smv_remote_whitelist = r"^origin$"
# Released pattern: tags are considered released versions
smv_released_pattern = r"^tags/v\d+\.\d+\.\d+$"
# Output directory format
smv_outputdir_format = "{ref.name}"


def mv_jupyter_execute(app, exception):
    """Move jupyter_execute into the version-specific html directory after build."""
    if exception is not None:
        return

    src = Path(app.outdir).parent / "jupyter_execute"
    dst = Path(app.outdir) / "jupyter_execute"

    if src.exists():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.move(src, dst)


def setup(app):
    app.connect("build-finished", mv_jupyter_execute)
