#!/usr/bin/env python3
"""Emit redirects for documentation URLs that earlier site layouts published.

The documentation has been restructured several times. Paths such as
``/notebooks/outline/elliptic_Fourier_analysis.html`` were live in earlier
releases, are still linked from papers, abstracts and blog posts, and now
return 404. ``doc/_redirects.toml`` maps each of those paths onto the docname
that replaced it; this script turns that map into redirect artifacts inside a
built site.

Output formats:

``--emit stubs`` (default)
    Write a small HTML file at each legacy path from ``doc/_redirects.toml``,
    holding a zero-delay ``meta refresh`` plus a canonical link to the target.
    This is the only mechanism available on GitHub Pages, which cannot serve a
    301 for an arbitrary path.

``--emit html-aliases``
    Walk the built tree instead of the map, and for every page the dirhtml
    builder publishes at ``<page>/index.html``, write a ``<page>.html`` stub
    redirecting to ``<page>/``. This keeps the old ``.html`` URLs alive after
    the html -> dirhtml switch. No map is involved; the alias set is derived
    entirely from what was built.

``--emit cloudflare``
    Write a ``_redirects`` file of real 301 rules at the site root, for hosts
    that support it.

Targets in the map are docnames rather than URLs, and this script resolves each
one against the tree that was actually built. The same map therefore yields
``/stable/api/datasets.html`` from an ``html`` build and
``/stable/api/datasets/`` from a ``dirhtml`` build, and switching builders needs
no edit to the map.

The ``stubs`` mode exits non-zero when a target docname is absent from the
build, or when a legacy path would overwrite a real page. A page rename that is
not reflected in the map therefore fails the documentation build rather than
shipping redirects that point at nothing.

Usage (SITE=doc/_build/html):
    uv run python scripts/gen_redirects.py --site-dir "$SITE"
    uv run python scripts/gen_redirects.py --site-dir "$SITE" --emit html-aliases
    uv run python scripts/gen_redirects.py --site-dir "$SITE" --emit cloudflare
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

# Lets a rerun tell its own output apart from a real page, so that generating
# twice into the same tree is safe while the guard against clobbering real
# content stays in force.
_MARKER = "generated by scripts/gen_redirects.py"

# A redirect stub must not carry `noindex`: the point of these files is to hand
# the accumulated ranking signals of the old URL over to the new one, and
# `noindex` would sever exactly that.
_STUB = """<!DOCTYPE html>
<!-- {marker} -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0; url={url}">
    <link rel="canonical" href="{canonical}">
    <title>Page moved</title>
  </head>
  <body>
    <p>This page has moved to <a href="{url}">{url}</a>.</p>
  </body>
</html>
"""


def _is_generated_stub(path: Path) -> bool:
    """True when `path` is output from an earlier run of this script."""
    try:
        with path.open(encoding="utf-8") as handle:
            return _MARKER in handle.read(len(_STUB) + len(_MARKER))
    except (OSError, UnicodeDecodeError):
        return False


def resolve(docname: str, version_root: Path, prefix: str) -> str:
    """Return the site-root-relative URL that ``docname`` is published at.

    Both builders write a directory index to ``<name>/index.html``, so index
    docnames resolve identically; only leaf pages differ, and those are probed
    in ``dirhtml`` order first.

    Raises
    ------
        LookupError: the docname is not present in the built tree.
    """
    if docname == "index":
        candidates = [(version_root / "index.html", f"{prefix}/")]
    elif docname.endswith("/index"):
        parent = docname[: -len("index")]
        candidates = [(version_root / f"{docname}.html", f"{prefix}/{parent}")]
    else:
        candidates = [
            (version_root / docname / "index.html", f"{prefix}/{docname}/"),
            (version_root / f"{docname}.html", f"{prefix}/{docname}.html"),
        ]
    for path, url in candidates:
        if path.is_file():
            return url
    raise LookupError(docname)


def plan(
    mapping: dict[str, str], site_dir: Path, version: str
) -> list[tuple[str, str]]:
    """Resolve every entry, or raise SystemExit listing all problems at once."""
    version_root = site_dir / version
    prefix = f"/{version}"
    if not version_root.is_dir():
        raise SystemExit(f"gen_redirects: no '{version}' directory under {site_dir}")

    resolved: list[tuple[str, str]] = []
    missing: list[str] = []
    clashing: list[str] = []

    for source, docname in sorted(mapping.items()):
        if not source.startswith("/"):
            raise SystemExit(
                f"gen_redirects: source path must start with '/': {source}"
            )
        existing = site_dir / source.lstrip("/")
        if existing.exists() and not _is_generated_stub(existing):
            clashing.append(source)
            continue
        try:
            resolved.append((source, resolve(docname, version_root, prefix)))
        except LookupError:
            missing.append(f"{source} -> {docname}")

    problems: list[str] = []
    if missing:
        problems.append(
            "target docnames absent from the built site (update doc/_redirects.toml "
            "to match the current page names):\n  " + "\n  ".join(missing)
        )
    if clashing:
        problems.append(
            "legacy paths that would overwrite a real page:\n  " + "\n  ".join(clashing)
        )
    if problems:
        raise SystemExit("gen_redirects: " + "\n\n".join(problems))
    return resolved


def emit_stubs(resolved: list[tuple[str, str]], site_dir: Path, base_url: str) -> None:
    for source, url in resolved:
        out = site_dir / source.lstrip("/")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            _STUB.format(
                marker=_MARKER, url=url, canonical=f"{base_url.rstrip('/')}{url}"
            ),
            encoding="utf-8",
        )


def emit_cloudflare(resolved: list[tuple[str, str]], site_dir: Path) -> None:
    lines = [f"{source}  {url}  301" for source, url in resolved]
    (site_dir / "_redirects").write_text("\n".join(lines) + "\n", encoding="utf-8")


# Sphinx-internal trees, not documentation pages: no .html alias is wanted for
# their directory indexes.
_ASSET_DIRS = frozenset(
    {"_static", "_sources", "_modules", "_images", "_downloads", "jupyter_execute"}
)


def emit_html_aliases(site_dir: Path, base_url: str) -> int:
    """Keep old ``foo.html`` URLs alive after the html -> dirhtml switch.

    The dirhtml builder publishes a leaf page ``foo`` as ``foo/index.html``,
    served at ``foo/``; its old URL ``foo.html`` no longer exists and 404s.
    For every ``<dir>/index.html`` under each version directory, write a stub
    at ``<dir>.html`` that redirects to ``<dir>/``, so links and bookmarks to
    the old form keep working and hand their ranking signal to the new URL.

    A directory-index page (docname ``<dir>/index``) is published at the same
    ``<dir>/index.html`` path under both builders and does not break; the stub
    written for it (``<dir>.html``) is a harmless additional alias, not a
    recreation of a URL that ever 404'd.

    Returns the number of stubs written.
    """
    written = 0
    for version_dir in sorted(p for p in site_dir.iterdir() if p.is_dir()):
        canonical_base = f"{base_url.rstrip('/')}/{version_dir.name}"
        for index_file in version_dir.rglob("index.html"):
            rel = index_file.parent.relative_to(version_dir)
            if not rel.parts or rel.parts[0] in _ASSET_DIRS:
                continue
            alias = version_dir / f"{rel.as_posix()}.html"
            if alias.exists():
                continue
            # Relative refresh target keeps the stub version-independent; the
            # canonical link is absolute so search engines consolidate onto the
            # new URL. Same no-noindex rule as the legacy redirect stubs.
            alias.write_text(
                _STUB.format(
                    marker=_MARKER,
                    url=f"{rel.parts[-1]}/",
                    canonical=f"{canonical_base}/{rel.as_posix()}/",
                ),
                encoding="utf-8",
            )
            written += 1
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate legacy URL redirects.")
    parser.add_argument(
        "--map", type=Path, default=Path("doc/_redirects.toml"), help="redirect map"
    )
    parser.add_argument(
        "--site-dir",
        type=Path,
        required=True,
        help="root of the built site, i.e. the directory holding version directories",
    )
    parser.add_argument(
        "--version", default="stable", help="version directory redirects point into"
    )
    parser.add_argument(
        "--emit", choices=("stubs", "cloudflare", "html-aliases"), default="stubs"
    )
    parser.add_argument("--base-url", default="https://doc.ktch.dev")
    args = parser.parse_args(argv)

    # html-aliases walks the built tree instead of the legacy map: every current
    # page keeps its old .html URL working after the dirhtml switch.
    if args.emit == "html-aliases":
        written = emit_html_aliases(args.site_dir, args.base_url)
        print(f"gen_redirects: wrote {written} redirects (html-aliases)")
        return 0

    mapping = tomllib.loads(args.map.read_text(encoding="utf-8"))["redirects"]
    resolved = plan(mapping, args.site_dir, args.version)

    if args.emit == "stubs":
        emit_stubs(resolved, args.site_dir, args.base_url)
    else:
        emit_cloudflare(resolved, args.site_dir)

    print(f"gen_redirects: wrote {len(resolved)} redirects ({args.emit})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
