"""Sphinx extension to inject ``noindex`` meta tag on low-value pages.

Pages generated by ``sphinx.ext.viewcode`` (``_modules/``), the general
index, module index, search page, and OpenSearch page provide little value
to search engines and can dilute indexing quality.  This extension adds
``<meta name="robots" content="noindex">`` to those pages so that crawlers
skip them when deciding what to index.
"""

from __future__ import annotations

import fnmatch
from typing import Any

from sphinx.application import Sphinx

# Page patterns that should receive a noindex meta tag.
_NOINDEX_PATTERNS: list[str] = [
    "_modules/*",
    "genindex",
    "py-modindex",
    "search",
    "opensearch",
]

_NOINDEX_TAG = '<meta name="robots" content="noindex">\n'


def _add_noindex_meta(
    app: Sphinx,
    pagename: str,
    templatename: str,
    context: dict[str, Any],
    doctree: Any,
) -> None:
    """``html-page-context`` callback — add noindex meta for matching pages."""
    for pattern in _NOINDEX_PATTERNS:
        if fnmatch.fnmatch(pagename, pattern):
            context["metatags"] = context.get("metatags", "") + _NOINDEX_TAG
            break


def setup(app: Sphinx) -> dict[str, Any]:
    app.connect("html-page-context", _add_noindex_meta)
    return {
        "version": "0.1",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
