# The shell script used to clear the cache of the GitHub CDN is forked from [hub-purge](https://github.com/mpyw/hub-purge/tree/master?tab=MIT-1-ov-file#readme) licensed under MIT License.
name: Clear Camo cache
on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * 0" # Every Sunday at 00:00(UTC)
jobs:
    purge:
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
        - name: Target URL(s)
          run: |
            echo "target: https://github.com/${GITHUB_REPOSITORY}/"
        - name: Purge cache from target URL(s)
          run: |
            curl -sL "https://github.com/${GITHUB_REPOSITORY}/" \
            | sed -n '/<script type="application\/json" data-target="react-partial.embeddedData">/,/<\/script>/p' \
            | sed 's/\\u003e/>/g; s/\\u002F/\//g; s/\\u0022/"/g; s/\\//g' \
            | grep -oE 'https?://camo.githubusercontent.com/[^"]+' \
            | while read -r url; do
                echo "purge: $url"
                curl -sX PURGE "$url" >/dev/null &
            done