# The shell script used to clear the cache of the GitHub CDN is forked from [hub-purge](https://github.com/mpyw/hub-purge/tree/master?tab=MIT-1-ov-file#readme) licensed under MIT License.
name: Clear Camo cache
on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * 0" # Every Sunday at 00:00(UTC)
jobs:
    purge:
      runs-on: ubuntu-latest
      steps:
        - run: echo "https://github.com/${GITHUB_REPOSITORY}/README.md"
        - name: Find camo urls from target page(s)
          id: find-camo-urls
          run: |
            urls=(curl -sL "https://github.com/${GITHUB_REPOSITORY}/README.md" \
            | sed -n '/<script type="application\/json" data-target="react-partial.embeddedData">/,/<\/script>/p' \
            | sed 's/\\u003e/>/g; s/\\u002F/\//g; s/\\u0022/"/g; s/\\//g' \
            | grep -oE 'https?://camo.githubusercontent.com/[^"]+') \
            && echo "urls=${urls}" >> ${GITHUB_OUTPUT}
        - env:
            URLS: ${{ steps.find-camo-urls.outputs.urls }}
          run: |
            echo "${URLS}"\
            && while read -r url; do
                echo "$url"
                curl -sX PURGE "$url" >/dev/null &
            done < "${URLS}"