name: Codecov
on: [push]
jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: ls
      - name: test2
        run: pwd
      - name: install pytest
        run: |
          python -m pip install flake8 pytest pytest-cov
      - name: install ktch
        run: pip install -e ../
      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
