name: Codecov
on: [push]
jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
