name: Codecov
on:
  push:
    branches: ["main"]
    paths:
      [
        "ktch/**",
        .github/workflows/test-codecov.yml,
        pyproject.toml,
        requirements.txt,
      ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Test with pytest
        run: uv run pytest --benchmark-skip --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v6
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
